IMDB Dataset of 50K Movie Reviews

In [1]:
import pandas as pd

In [2]:
data = "../IMDB Dataset.csv"
df = pd.read_csv(data)
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df = df.sample(frac=0.1, random_state=1)
df.shape

(5000, 2)

Converting to lower

In [4]:
df['review'] = df['review'].str.lower()
df.head()

                                                  review sentiment
26247  with no dead heroes you get stupid lines like ...  negative
35067  i thought maybe... maybe this could be good. a...  negative
34590  an elite american military team which of cours...  negative
16668  ridiculous horror film about a wealthy man (jo...  negative
12196  well, if you are one of those katana's film-nu...  positive

Removing HTML tags with regular expressions

In [5]:
import re
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

def remove_url(text):
    url_pattern = re.compile(r'http\S+|www\S+|https\S+', re.IGNORECASE)
    return url_pattern.sub(r'', text)

In [6]:
text  = "<html><head><title>A Title</title></head><body><h1>Header</h1><p>This is a paragraph.</p></body></html>"
remove_html_tags(text)

'A TitleHeaderThis is a paragraph.'

In [7]:
df["review"] = df["review"].apply(remove_html_tags)
df.head()

                                                  review sentiment
26247  with no dead heroes you get stupid lines like ...  negative
35067  i thought maybe... maybe this could be good. a...  negative
34590  an elite american military team which of cours...  negative
16668  ridiculous horror film about a wealthy man (jo...  negative
12196  well, if you are one of those katana's film-nu...  positive

Remove Punctuation

In [8]:
import string, time
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [9]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', exclude))

In [10]:
txt = 'Text. With. Punch,,.'
print(remove_punctuation(txt))

Text With Punch

In [11]:
df['review'] = df['review'].apply(remove_punctuation)
df.head()

                                                  review sentiment
26247  with no dead heroes you get stupid lines like ...  negative
35067  i thought maybe maybe this could be good an ea...  negative
34590  an elite american military team which of cours...  negative
16668  ridiculous horror film about a wealthy man joh...  negative
12196  well if you are one of those katanas filmnuts ...  positive

Handling Abbreviations

In [12]:
chat_words = {
    'AFAIK':'As Far As I Know',
    'AFK':'Away From Keyboard',
    'ASAP':'As Soon As Possible',
    "FYI": "For Your Information",
    "ASAP": "As Soon As Possible",
    "BRB": "Be Right Back",
    "BTW": "By The Way",
    "OMG": "Oh My God",
    "IMO": "In My Opinion",
    "LOL": "Laugh Out Loud",
    "TTYL": "Talk To You Later",
    "GTG": "Got To Go",
    "TTYT": "Talk To You Tomorrow",
    "IDK": "I Don't Know",
    "TMI": "Too Much Information",
    "IMHO": "In My Humble Opinion",
    "ICYMI": "In Case You Missed It",
    "AFAIK": "As Far As I Know",
    "BTW": "By The Way",
    "FAQ": "Frequently Asked Questions",
    "TGIF": "Thank God It's Friday",
    "FYA": "For Your Action",
    "ICYMI": "In Case You Missed It",
}

In [ ]:
def abbreviation_conversion(text):
    words = text.split()
    new_text = []
    for word in words:
        
        if word.upper() in chat_words:
          
            new_text.append(chat_words[word.upper()])
        else:
            new_text.append(word)
    return " ".join(new_text)

In [ ]:
abbreviation_conversion("FYI I will be AFK for a while. ASAP I will get back to you. TTYL")

'For Your Information I will be Away From Keyboard for a while. As Soon As Possible I will get back to you. Talk To You Later'

In [15]:
pip install textblob

Requirement already satisfied: textblob in c:\users\arnav\onedrive\documents\projects\genai tutorials\venv\lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\users\arnav\onedrive\documents\projects\genai tutorials\venv\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\arnav\onedrive\documents\projects\genai tutorials\venv\lib\site-packages (from nltk>=3.9->textblob) (8.1.7)
Requirement already satisfied: joblib in c:\users\arnav\onedrive\documents\projects\genai tutorials\venv\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\arnav\onedrive\documents\projects\genai tutorials\venv\lib\site-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\arnav\onedrive\documents\projects\genai tutorials\venv\lib\site-packages (from nltk>=3.9->textblob) (4.67.0)
Requirement already satisfied: colorama in c:\users\arnav\onedrive\documents\projects\genai tutorials\venv\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Correcting Spellings

In [16]:
from textblob import TextBlob
incorrect_text = "I havv goood speling"
corrected_text = TextBlob(incorrect_text).correct()
print(corrected_text)

I have good spelling

Removing Stopwords

In [17]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\arnav\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [18]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    words = text.split()
    new_text = []
    for word in words:
        if word not in stop_words:
            new_text.append(word)
    return " ".join(new_text)

In [19]:
remove_stopwords("This is a sample sentence, showing off the stop words filtration.")

'This sample sentence, showing stop words filtration.'

In [20]:
df['review'] = df['review'].apply(remove_stopwords)
df.head()

                                                  review sentiment
26247  dead heroes get stupid lines like woefully aby...  negative
35067  thought maybe maybe could good early appearanc...  negative
34590  elite american military team course happens in...  negative
16668  ridiculous horror film wealthy man john carrad...  negative
12196  well one katanas filmnuts like sure appreciate...  positive

Remove Emojis (Uni-Code characters)

In [21]:
def remove_emojis(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [22]:
remove_emojis("This is a test 😊. This is only a test 🚀!")

'This is a test . This is only a test !'

Retaining Emoji sentiments

In [23]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ---------------------------------------- 0.0/590.6 kB ? eta -:--:--
   --------------------------------------- 590.6/590.6 kB 20.5 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.14.1

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
import emoji
print(emoji.demojize("This is a test 😊. This is only a test 🚀!"))

This is a test :smiling_face_with_smiling_eyes:. This is only a test :rocket:!